services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: starboard-discord-bot
    pull_policy: always
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_PATH=/data
    volumes:
      - ./db:/data